name: build

on:
  push:
    branches:
    - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [RM2100]
        toolchain: [mipsel-linux-musl]
    steps:
      - uses: actions/checkout@master
      - uses: hendrikmuhs/ccache-action@master
        with:
          key: ${{ matrix.target }}-${{ matrix.toolchain }}
      - uses: actions/setup-go@master
        with:
          go-version: '1.23.5'
          check-latest: true
          cache: false
      - name: Prepare environment
        run: |
          sudo apt-get update && sudo apt-get install -y unzip libtool-bin ccache curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio bc zip git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin liblzma-dev
          echo "ROOTDIR=${{ github.workspace }}/trunk" >> $GITHUB_ENV
          echo "Compilation_time=$(TZ='Asia/Shanghai' date +%Y%m%d)" >> $GITHUB_ENV
      - name: Start build firmware
        run: |
          make ${{ matrix.target }} TOOLCHAIN=${{ matrix.toolchain }}
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.target }}-${{ matrix.toolchain }}
          path: trunk/images/*.trx
      - uses: ncipollo/release-action@master
        with:
          commit: master
          tag: ${{ env.Compilation_time }}
          artifacts: trunk/images/*.trx
          allowUpdates: true
          omitBodyDuringUpdate: true
      - uses: Mattraks/delete-workflow-runs@master
        with:
          retain_days: 0
          keep_minimum_runs: 1
